cache:
  directories:
  - node_modules
language: node_js 
node_js:
  7 
branches:
  only: 
  - master 
script: 
- npm install 
- npm run build # build project
deploy:
  provider: firebase
  token:
    secure: "${FIREBASE_TOKEN}"