cache:
  directories:
    - node_modules
language: node_js 
node_js:
  6
branches:
  only: 
    - master 
before_script:
  - npm install -g firebase-tools
  - npm install
script: 
  - npm run build # build project
deploy:
  provider: firebase
  token:
    secure: "${FIREBASE_TOKEN}"